### PR TITLE
feat: bump to v8 11.1

### PR DESCRIPTION
**Pull request by gengjiawen**

### CODE REVIEW

**Comment by gengjiawen** [comment]
```console
v8-cmake/v8/src/objects/instance-type-inl.h:183:24: error: out-of-line definition of 'IsJSDurationFormat' does not match any declaration in 'v8::internal::HeapObject'
```

@bnoordhuis not sure how to fix this one

**Comment by bnoordhuis** [comment]
You probably need to remove src/objects/js-duration-format.tq from torque_files around line 850 in CMakeLists.txt, possibly others as well.

**Comment by bnoordhuis** [comment]
Ouch...
```
/home/runner/work/v8-cmake/v8-cmake/v8/src/heap/heap-allocator-inl.h:162:18: error: inlining failed in call to always_inline ‘v8::internal::AllocationResult v8::internal::HeapAllocator::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment)’: function not inlinable
```
Apparently `V8_INLINE` evaluates to `inline __attribute__((always_inline))` instead of just `inline` now. I have choice words for people who insist on using `always_inline` but grumbles aside...

I'd be okay with floating a patch in patches/ that sets `V8_HAS_ATTRIBUTE_ALWAYS_INLINE` to 0 in v8/include/v8config.h (defined in two places.)

**Comment by bnoordhuis** [comment]
Left a comment on an existing always_inline bug report: https://bugs.chromium.org/p/v8/issues/detail?id=13073#c19

**Comment by gengjiawen** [comment]
> Ouch...
> 
> ```
> /home/runner/work/v8-cmake/v8-cmake/v8/src/heap/heap-allocator-inl.h:162:18: error: inlining failed in call to always_inline ‘v8::internal::AllocationResult v8::internal::HeapAllocator::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment)’: function not inlinable
> ```
> 
> Apparently `V8_INLINE` evaluates to `inline __attribute__((always_inline))` instead of just `inline` now. I have choice words for people who insist on using `always_inline` but grumbles aside...
> 
> I'd be okay with floating a patch in patches/ that sets `V8_HAS_ATTRIBUTE_ALWAYS_INLINE` to 0 in v8/include/v8config.h (defined in two places.)

Also interesting this is only happens in GCC, clang on linux is fine.

**Comment by bnoordhuis** [comment]
It's probably missing src/base/platform/memory-protection-key.cc from v8_libbase. Can be unconditional, doesn't have to be filtered on OS or anything.

**Comment by gengjiawen** [comment]
> It's probably missing src/base/platform/memory-protection-key.cc from v8_libbase. Can be unconditional, doesn't have to be filtered on OS or anything.

Yeap. I forget to revert some local patch.

**Review by bnoordhuis — APPROVED** [review]
Nice work, LGTM!

**Pull request merged**
