### PR TITLE
Ia32 8.7

### PR DESCRIPTION
**Pull request by petebannister**

### CODE REVIEW

**Comment by petebannister** [comment]
Builds for IA32.  I originally was doing this on master but had build issues.  I think in hindsight that was due to a problem with MAX_PATH on Windows.  So I merged the changes on the 8.7 branch for now.

**Comment by petebannister** [comment]
See issue #42

**Comment by petebannister** [comment]
FYI this does not fix the path limitation issue - I just was using an older version of V8 that still worked!

Thei PR is just to make Win32 builds on MSVC work

**Comment by bnoordhuis** [comment]
I'm going to ahead and close this because we've since upgraded to newer versions.

The path issue was fixed in #82 but, caveat emptor, upstream V8 has announced they'll be dropping support for msvc and gcc in September and so will we, in all likelihood.

**Pull request closed without merging**
