### PR TITLE
Use precompiled headers to improve compile times.

### PR DESCRIPTION
**Pull request by petebannister**
Drastic improvement to compile time with MSVC2019.  You may want to adjust the way that USE_PRECOMPILED_HEADERS gets set to restrict the compilers it applies to.  I have only tried this with MSVC.  I believe GCC implements PCH these days.  Not sure r.e. clang -- I think it does a good job without them.

### CODE REVIEW

**Comment by petebannister** [comment]
On my system, PCH means full built takes around 8 minutes, vs around 50 minutes for non-pch build.

**Comment by petebannister** [comment]
Mentioned this in issue #5 also

**Comment by gengjiawen** [comment]
Wow, amazing work.

**Comment by gengjiawen** [comment]
Any chance we can also try this on gcc in CI ?

**Comment by gengjiawen** [comment]
@petebannister Do you have any interest bring this to node.js ? Currently we have pch, but not this kind of fast. https://github.com/nodejs/node/blob/master/tools/msvs/pch/v8_pch.h

**Review by gengjiawen — APPROVED** [review]

**Comment by petebannister** [comment]
> @petebannister Do you have any interest bring this to node.js ? Currently we have pch, but not this kind of fast. https://github.com/nodejs/node/blob/master/tools/msvs/pch/v8_pch.h

Node itself is not something I've built before... perhaps it should use v8-cmake instead? ;)  It is so much easier to build (and debug the build) than the GN build and also takes up way less disk space.

I'm using this to embed v8 into an application (as a conan package).

A big saving was a specific PCH for the torque generated code (which can't apply to all libraries).  There are some weird effects when including some headers in the PCH that break the build.  Some files don't have inclusion guards or there are definition ordering issues.  In some cases there are some globbed headers but its risky due to potential include ordering breakage.

**Comment by gengjiawen** [comment]
> > @petebannister Do you have any interest bring this to node.js ? Currently we have pch, but not this kind of fast. [https://github.com/nodejs/node/blob/master/tools/msvs/pch/v8_pch.h](https://github.com/nodejs/node/blob/master/tools/msvs/pch/v8_pch.h?rgh-link-date=2021-01-27T11%3A51%3A59Z)
> 
> Node itself is not something I've built before... perhaps it should use v8-cmake instead? ;) It is so much easier to build (and debug the build) than the GN build and also takes up way less disk space.
> 
> I'm using this to embed v8 into an application (as a conan package).
> 
> A big saving was a specific PCH for the torque generated code (which can't apply to all libraries). There are some weird effects when including some headers in the PCH that break the build. Some files don't have inclusion guards or there are definition ordering issues. In some cases there are some globbed headers but its risky due to potential include ordering breakage.

Thanks for the explaination. @bnoordhuis What do you think of this ?

Also, master is v8 8.8 now :)

**Comment by gengjiawen** [comment]
I tried on gcc and clang, also works, thx.

**Pull request merged**
