### PR TITLE
8.9.255.9

### PR DESCRIPTION
**Pull request by bnoordhuis**

### CODE REVIEW

**Comment by gengjiawen** [comment]
Upstream: https://chromium-review.googlesource.com/c/v8/v8/+/2711152

**Comment by bnoordhuis** [comment]
@gengjiawen I don't really have time at the moment to investigate and push this through but if you want to pick up where I left off, I'm happy to make you co-maintainer.

**Comment by gengjiawen** [comment]
> @gengjiawen I don't really have time at the moment to investigate and push this through but if you want to pick up where I left off, I'm happy to make you co-maintainer.

Sure.

**Comment by bnoordhuis** [comment]
@gengjiawen No pressure at all but I was wondering if you managed to make any progress on this? You received (and accepted) the invitation, right?

**Comment by gengjiawen** [comment]
> @gengjiawen No pressure at all but I was wondering if you managed to make any progress on this? 

Not fully into it. Looks like this part not working 
```cmake
if(WIN32)
  list(APPEND heap-sources
    $<${is-arm64}:v8/src/heap/base/asm/arm64/push_registers_masm.S>
    $<${is-ia32}:v8/src/heap/base/asm/ia32/push_registers_masm.S>
    $<${is-x64}:v8/src/heap/base/asm/x64/push_registers_masm.S>
  )
```			

> You received (and accepted) the invitation, right?

Yeap.

**Comment by gengjiawen** [comment]
@bnoordhuis looks build passed.

**Pull request merged**
