### PR TITLE
ci test

### PR DESCRIPTION
**Pull request by bnoordhuis**

### CODE REVIEW

**Comment by gengjiawen** [comment]
Looks like still one symbol not resovled, should we make a patch to `heap-inl.h`

**Comment by bnoordhuis** [comment]
I was just looking at that. It's odd because `GetHeapFromWritableObject()` is defined inline in `src/execution/isolate-utils-inl.h`. Maybe it isn't included in `src/heap/heap.cc`.

**Comment by bnoordhuis** [comment]
We're down to this now so that's progress. :-)
```
2020-04-15T14:10:52.1677567Z v8_base_without_compiler.lib(isolate.obj) : error LNK2001: unresolved external symbol v8_Default_embedded_blob_ [D:\a\v8-cmake\build\d8.vcxproj]
2020-04-15T14:10:52.3178730Z v8_base_without_compiler.lib(isolate.obj) : error LNK2001: unresolved external symbol v8_Default_embedded_blob_size_ [D:\a\v8-cmake\build\d8.vcxproj]
2020-04-15T14:10:52.3899846Z D:\a\v8-cmake\build\Debug\d8.exe : fatal error LNK1120: 2 unresolved externals [D:\a\v8-cmake\build\d8.vcxproj]
```

**Comment by gengjiawen** [comment]
> 2020-04-15T14:10:52.1677567Z v8_base_without_compiler.lib(isolate.obj) : error LNK2001: unresolved external symbol v8_Default_embedded_blob_ [D:\a\v8-cmake\build\d8.vcxproj]

From the error should `${D}/src/snapshot/embedded/embedded-empty.cc` moved to `snapshot-sources` ?

**Comment by gengjiawen** [comment]
Also, on my PC using this patch the error still is https://github.com/bnoordhuis/v8-cmake/issues/10#issuecomment-613792742, not sure is because I am using Ninja on windows.

**Comment by gengjiawen** [comment]
Looks like those two the same problem.

> LINK : fatal error LNK1181: ????????"CMakeFiles\v8_snapshot.dir\embedded.S.obj"

> 2020-04-15T14:10:52.1677567Z v8_base_without_compiler.lib(isolate.obj) : error LNK2001: unresolved external symbol v8_Default_embedded_blob_ [D:\a\v8-cmake\build\d8.vcxproj]

on windows `embedded.S.obj` not generated, so msvc can't find the related symbol.

**Comment by gengjiawen** [comment]
Ok, looks like we hit a cmake bug: https://gitlab.kitware.com/cmake/cmake/issues/18912.

**Comment by gengjiawen** [comment]
Maybe related to this: https://gitlab.kitware.com/cmake/cmake/issues/18912. We need extra work on windows to integrate asm.

**Comment by gengjiawen** [comment]
based on this, windows build finally works. I will send you a PR.

**Comment by bnoordhuis** [comment]
Fixed by #18!

**Pull request closed without merging**
