### PR TITLE
feat: bump to v8 9.6

### PR DESCRIPTION
**Pull request by gengjiawen**
```
/Users/jiawengeng/code/v8-cmake/v8/src/compiler/code-assembler.h:163:1: error: unknown type name 'WasmValueObject'; did you mean 'WasmTableObject'?
HEAP_OBJECT_ORDINARY_TYPE_LIST(OBJECT_TYPE_CASE)
```

any hint for this error ? I found the object exist on `debug-interface.h`, and included.

cc @bnoordhuis

### CODE REVIEW

**Comment by bnoordhuis** [comment]
You probably need to add v8/src/debug/debug-wasm-objects{.cc,.h,-inl.h}.

**Comment by gengjiawen** [comment]
> You probably need to add v8/src/debug/debug-wasm-objects{.cc,.h,-inl.h}.

Found a silly mistake I have taken, now stuck on

```console
/Users/jiawengeng/code/v8-cmake/v8/src/builtins/setup-builtins-internal.cc:336:3: error: no member named 'kLdaNamedPropertyNoFeedback' in 'v8::internal::interpreter::Bytecode'
  BUILTIN_LIST(BUILD_CPP, BUILD_TFJ, BUILD_TFC, BUILD_TFS, BUILD_TFH, BUILD_BCH,
```

I have found `kLdaNamedProperty`, not sure where `NoFeedback` comes from.

**Comment by gengjiawen** [comment]
classic fails only on MSVC 😓

**Comment by gengjiawen** [comment]
Thanks to the old issue: https://github.com/bnoordhuis/v8-cmake/issues/10.

**Comment by gengjiawen** [comment]
Upstream patch: https://chromium-review.googlesource.com/c/v8/v8/+/3366367.

**Review by bnoordhuis — APPROVED** [review]
Nice, LGTM 👍

**Pull request merged**
